POST http://localhost:9090/api/v1/auth/register
Content-Type: application/json

{
  "name" :"nama 7",
  "email": "nama7@mail.com",
  "password": "testpassword"
}

###
POST http://localhost:9090/api/v1/auth/login
Content-Type: application/json

{
  "email": "nama1@mail.com",
  "password": "testpassword"
}

###

PUT http://localhost:9090/api/v1/artwork/upload
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY5OTAxNjEyMH0.rHtpXYX94p-nJpijU-EC5DLWE9MiqY4mmWwMhfuT2y4
Content-Type: multipart/form-data

{
  "title": "ok",
  "description": "testpassword",
  "image":"-"
}


