POST http://localhost:8090/api/v1/auth/register
Content-Type: application/json

{
  "name" :"nama 7",
  "email": "nama7@mail.com",
  "password": "testpassword"
}

###
POST http://localhost:8090/auth/login
Content-Type: application/json

{
  "email": "nama1@mail.com",
  "password": "testpassword"
}


